name: nice_shot
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  get_it: ^7.2.0
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  camera:
  chewie: ^1.3.5
  video_player: ^2.4.5
  internet_connection_checker: ^0.0.1+4
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  assets_audio_player: ^3.0.5
  flutter_slidable: ^2.0.0
  external_path: ^1.0.1
  permission_handler: any
  video_trimmer:
    git:
      url: https://github.com/mo7elessi/video_trimmer
  flutter_uploader:
    git:
      url: https://github.com/mo7elessi/flutter_uploader
  share: ^2.0.4
  video_thumbnail: ^0.5.3
  flutter_local_notifications: ^11.0.1
  awesome_notifications: ^0.6.21
  flutter_video_info: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
  fonts:
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
